/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                    '#f9f9f7',
        'surface-bright':             '#f9f9f7',
        'surface-dim':                '#d4dcd8',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f2f4f2',
        'surface-container':          '#ecefec',
        'surface-container-high':     '#e5e9e6',
        'surface-container-highest':  '#dee4e0',
        'surface-variant':            '#dee4e0',
        'surface-tint':               '#595f66',
        'background':                 '#f9f9f7',
        'on-background':              '#2d3432',
        'on-surface':                 '#2d3432',
        'on-surface-variant':         '#5a605e',
        'inverse-surface':            '#0d0f0e',
        'inverse-on-surface':         '#9c9d9b',
        'primary':                    '#595f66',
        'primary-dim':                '#4d5359',
        'primary-container':          '#dde3eb',
        'primary-fixed':              '#dde3eb',
        'primary-fixed-dim':          '#cfd5dd',
        'on-primary':                 '#f4f8ff',
        'on-primary-container':       '#4c5259',
        'on-primary-fixed':           '#3a4046',
        'on-primary-fixed-variant':   '#565c63',
        'inverse-primary':            '#f1f7ff',
        'secondary':                  '#586068',
        'secondary-dim':              '#4c545c',
        'secondary-container':        '#dbe3ed',
        'secondary-fixed':            '#dbe3ed',
        'secondary-fixed-dim':        '#cdd5de',
        'on-secondary':               '#f6f9ff',
        'on-secondary-container':     '#4b535a',
        'on-secondary-fixed':         '#384048',
        'on-secondary-fixed-variant': '#545c64',
        'tertiary':                   '#5c5f64',
        'tertiary-dim':               '#505358',
        'tertiary-container':         '#f1f4f9',
        'tertiary-fixed':             '#f1f4f9',
        'tertiary-fixed-dim':         '#e3e5eb',
        'on-tertiary':                '#f7f9fe',
        'on-tertiary-container':      '#595c61',
        'on-tertiary-fixed':          '#464a4e',
        'on-tertiary-fixed-variant':  '#63666b',
        'outline':                    '#767c79',
        'outline-variant':            '#adb3b0',
        'error':                      '#9f403d',
        'error-dim':                  '#4e0309',
        'error-container':            '#fe8983',
        'on-error':                   '#fff7f6',
        'on-error-container':         '#752121',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg:      '0px',
        xl:      '0px',
        full:    '9999px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
